[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
soladz = "DLTNDktGdPk1ZAUxDGCSwwdRSuvbvD5V6sF3ow27QURx"

[registry]
url = "https://mainnet.helius-rpc.com/?api-key=af96dbd7-552e-4f4b-8b34-e607f792a78c"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
